#!/usr/bin/env ruby

path = File.path(ARGV.first)
commits = File.readlines(path, chomp: true).map do |line|
  line.split("pick ")[1].split(" ")[0]
end

puts "Processing #{commits.length} commits."

puts "First commit sha is: #{commits[0]}"
puts "Last commit sha is: #{commits[-1]}"

File.open("reordered_commits_#{Time.now.to_i}.txt", "w") do |file|
  commits.each do |commit|
    file << commit + "\n"
  end
end